apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-app-dev
namePrefix: dev-
images:
- name: edbdmss/gitops-app
  newName: edbdmss/gitops-app
  newTag: sha-31a5312

replicas:
- count: 1
  name: dev-gitops-app
